### ISSUE TITLE
How to select the parameter k and n properly?

### ISSUE THREAD

**Issue by gottaMe** [reinhardh/dna_rs_coding#1]
Hello,
First of all thanks for this great project very much, but I have a problem about how to select the parameter k and n properly?

Taking your 'example 1' as an example, the original file is 181142 Bytes, corresponding to 181142 * 8 bits. However, you selected the parameter k=9000, and I calculated the total bits that can be stored in this way are 9000 * 12 * 14 bits because of the nuss = 12 and m_o = 14. It far exceeds the number 181142 * 8.

So, Why did you choose this parameter? Look forward to your kind reply.

**Comment by reinhardh** [comment]
With the chosen parameters, you could store 9000*14*12 = 1 512 000 bits. The file has 181 142 * 8 = 1 449 136 bits, so the file can be stored, and takes up 96% of the available storage space, so the number of bits that can be stored does not far exceed the number of bits that can be stored. You could make K slightly smaller if you want to get slightly more redundancy and slightly more resilience to errors, and take up 100% of the space available.

**Comment by gottaMe** [comment]
Thanks for your reply! but I get another problem when I want to use this program to encode my data, which consists of 19 characters.

I use the parameters shown in the following picture to encode the 19 bytes, and it works well.
![correct](https://user-images.githubusercontent.com/48898689/105842875-d9d11180-6011-11eb-9754-b41f20e555a9.png)
I think this can be regarded as enough to encode these 19 characters when k=5.

However, I get no output when I change the parameter k to 6.
![error](https://user-images.githubusercontent.com/48898689/105843313-7eebea00-6012-11eb-9bcb-804ab931e87b.png)

Then I use other parameters, e.g k=6 and n=7, k=7 and n=7, but it seems to still have some problems.
![error1](https://user-images.githubusercontent.com/48898689/105848279-b8742380-6019-11eb-926e-f7b5b365a088.png)
![error2](https://user-images.githubusercontent.com/48898689/105848301-bdd16e00-6019-11eb-9fe2-7b1d71b4b3ec.png)

So I don’t know what went wrong. Could you propose any workarounds?

Thanks

**Comment by gottaMe** [comment]
Thanks for your reply! but I get another problem when I want to use this program to encode my data, which consists of 19 characters.

I use the parameters k=5, n=6, K=11, N=14, nuss=3 to encode the 19 bytes, and it works well.
I think this can be regarded as enough to encode these 19 characters when k=5.

However, I get no output when I change the parameter k to 6.

Then I use other parameters, e.g k=6 and n=7, k=7 and n=7, but it seems to still have some problems.

So I don’t know what went wrong. Could you propose any workarounds?

Thanks

**Comment by reinhardh** [comment]
Please read the paper https://www.nature.com/articles/s41467-020-19148-3 which describes which parameters are allowed and which are not allowed. You're trying to use the code for a regime in which it would not make sense to use it, and for which it is therefore not designed to work. Specifically, n=k=7 means there is no redundancy in the outer code.

**Comment by gottaMe** [comment]
ok, thanks for your help!

**Comment by gottaMe** [comment]
Hi, I read the paper you recommended and also read the paper "Reading and writing digital data in DNA" published on Nature Protocol. I'm very interested in that work, and try to use the .fastq file that provided by this paper to recover the original file "Linda reformat.zip".

I use the following command to try to recover the file:

> ./texttodna --n=12472 --k=9000 --nuss=12 --K=32 --N=34 --decode --numblocks=1 --fastq_infile=../data/linda_encoded_iSeq_S3_L001_R1_001.fastq --output=../data/paper_recovered.zip

but I got the following messages:

> number of reads: 1571256
inner code: 0.805399 errors on average corrected per sequence
12471 many erasures in block 0 of length 12472

The errors corrected by inner code seem to be normal, but the erasures examined by outer code seem to be abnormal. So I don’t know what went wrong...

many thanks for your help,

**Comment by reinhardh** [comment]
It looks like you are following the example in our paper ``reading and writing digital data in DNA''. The code that is supplied with the paper can be downloaded at:
https://static-content.springer.com/esm/art%3A10.1038%2Fs41596-019-0244-5/MediaObjects/41596_2019_244_MOESM3_ESM.zip
The version of the code used in the paper might differ in a minor detail, which is the seed of the random sequence that is multiplied with the data. If you want to decode the file
linda_encoded_iSeq_S3_L001_R1_001.fastq
then please run the code above. 
That successfully decodes and gives the output: 

fastq infile:  ../data/linda_encoded_iSeq_S3_L001_R1_001.fastq
outfile: ../data/paper_recovered.zip
numblocks: 1
assume fastq file as input format
start decode..
number of reads: 1571256
inner code: 0.805399 errors on average corrected per sequence
1351 many erasures in block 0 of length 12472
remove random sequence
decoding block 0
	part 0/12
	part 1/12
	part 2/12

Thanks for your interest in our work, I'm happy to answer your questions regarding the paper, but please write an email if it pertains to the paper.
