### ISSUE TITLE
Decoding Error

### ISSUE THREAD

**Issue by Zahra-lucia** [reinhardh/dna_rs_coding#2]
[](url)
![last step](https://user-images.githubusercontent.com/74935081/112217149-fb720200-8c2a-11eb-9d18-b090030c9300.jpeg)
could you please help me know the reason it is stopping at this line without decoding though I have followed all  the mentioned steps

**Comment by jorsn** [comment]
Have you looked at https://github.com/reinhardh/dna_rs_coding/issues/1#issuecomment-770283598?

Is it stopping or does it just take a while? In the image it hasn't terminated so far. For debugging you could e.g. set breakpoints in `gdb` or simply add some debug messages at the loop after this location:

https://github.com/reinhardh/dna_rs_coding/blob/master/include/encodedecode.hpp#L443

This is the point where you got according to the messages. But depending on your computer, I'd imagine that decoding a (16383, 12911, 2^14) code (shortened to (12472, 9000)) could take a while.

**Comment by reinhardh** [comment]
Thanks jorsn; exactly, in this example, the code runs correctly, since the number of errors is large (1882 errasures) it will just take a while depending on the computer.

**Comment by Zahra-lucia** [comment]
It has worked successfully but it has taken 2 hours for encoding and decoding and after  I edited the code in texttodna (setting const unsigned M = n*numblocks*6; to const unsigned M = n*numblocks*12) as reinhardh told me thanks a lot for helping , that what also happened after trying example 2 but even after waiting 4 hours it stopped at decoding block 2 part 4 it maybe takes more much time. I think the problem is the machine I am using.
