### ISSUE TITLE
sequence simulator

### ISSUE THREAD

**Issue by Zahra-lucia** [reinhardh/dna_rs_coding#3]
is is true to say that  disturb with the constraints of k and m are the sequence simulator, As I have understood that disturb only adds substitution errors. Is there a place that shows that it adds  addition or deletion errors? I would so pleasured for your kind help.

**Comment by reinhardh** [comment]
The disturb function only adds substitution errors, since this code is designed for that. If you are interested in deletions and deletions, here is code that is designed for that: https://github.com/MLI-lab/noisy_dna_data_storage
